# @formatter:off
version: 'CI.{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  CI: true

build_script:
  - gradlew build

notifications:
  - provider: Email
    to:
      - ray.eldath@outlook.com
    on_build_success: false